// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcodnrNu3ko7QpAQS4iqk_NaESobO3pVA',
    appId: '1:173767791600:web:c46db5977e6d26c2d10335',
    messagingSenderId: '173767791600',
    projectId: 'instagram-c05c9',
    authDomain: 'instagram-c05c9.firebaseapp.com',
    storageBucket: 'instagram-c05c9.firebasestorage.app',
    measurementId: 'G-N60DMB4ZY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSYDBPSTsT_4gB4Qb5yepsB_MhCMEYC9o',
    appId: '1:173767791600:android:78d65a12bab3c39dd10335',
    messagingSenderId: '173767791600',
    projectId: 'instagram-c05c9',
    storageBucket: 'instagram-c05c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqBhxHuVhoFGOv2iTeDGvVcTD8JckolU',
    appId: '1:173767791600:ios:a3bb234459405be9d10335',
    messagingSenderId: '173767791600',
    projectId: 'instagram-c05c9',
    storageBucket: 'instagram-c05c9.firebasestorage.app',
    iosBundleId: 'com.example.instagram107',
  );
}
